version: "3"
services:
  rabbit_mq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: demo
    ports:
      - "20000:15672"
      - "20001:5672"
  db:
    image: postgres:12.2
    ports:
      - 20002:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: counters
  word.counter.worker:
    build: ../WordCounter.Worker/
    depends_on:
      - rabbit_mq
      - db
  word.counter.api:
    build: ../WordCounter.Api/
    depends_on:
      - rabbit_mq
      - db
    ports:
      - 5000:5000